server:
  port: 80
spring:
  application:
    name: nacos-comsumer-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'

#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者)
service-url:
  nacos-user-service: http://cloud-nacos-provider
  nacos-config-service: http://cloud-nacos-config