server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
    # 路由网关配置
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
        #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-nacos-openfeign #匹配后提供服务的路由地址
          predicates:
#            - Path=/payment/get/**         # 断言，路径相匹配的进行路由
            - Method=GET,POST


management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true # 激活Sentinel对Feign的支持